### ISSUE TITLE
How to play the sound in silence

### ISSUE THREAD

**Issue by condef5** [hu-ke/react-audio-spectrum#1]
Hi, thanks for this amazing work, I want to be able to play the music in silence, how could I do it.

**Comment by hu-ke** [comment]
if you play the music in silence, you can't  **getByteFrequencyData** from the **analyser** so that the spectrum won't be displayed on the canvas.

**Comment by jsejcksn** [comment]
I think you can do this by just not `connect`ing it to an [`AudioDestinationNode`](https://developer.mozilla.org/en-US/docs/Web/API/AudioDestinationNode).

Maybe it can become a boolean prop like `silent`: `true | false`?

**Comment by ericwooley** [comment]
Having a silent would be incredibly helpful, since I'm trying to use this to display someones own mic activity.

I'm trying to figure out what @jsejcksn is suggesting. Can I manipulate the Audio element in some way to achieve silence while visiualizing the sound?

**Comment by hu-ke** [comment]
v0.1.5 supports playing silent mode.

**Comment by jsejcksn** [comment]
> v0.1.5 supports playing silent mode.

Commit refs:

- https://github.com/hu-ke/react-audio-spectrum/commit/5c73e6cd521a94fc3cb5e89dcc421a49dc22c5c2
- https://github.com/hu-ke/react-audio-spectrum/commit/b0e1b3079de1b91f0f71e39c78f3c609090b7135
