### ISSUE TITLE
Getting visualizer from video/videostream

### ISSUE THREAD

**Issue by Nitzahon** [hu-ke/react-audio-spectrum#15]
Is there anyway to get the audio spectrum to work with video, I want to display some feedback to the user so he knows that the recording is picking up his mic

**Comment by oliviergfarley** [comment]
is this solved? i want to pass the audioStream comming from `    navigator.mediaDevices
      .getUserMedia({ video: false, audio: true })`

**Comment by Nitzahon** [comment]
I ended up going in a different direction with this. Thank you.

**Comment by JosepSalvat** [comment]
@Nitzahon What did you do? I'm having the same issue

**Comment by Nitzahon** [comment]
I ended up using a different solution. Using hark(link: https://www.npmjs.com/package/hark) I would connect it to the audio stream, get the volume level from it, and then adjust the width of a div to simulate  a visualizer bar

**Comment by Nitzahon** [comment]
> @Nitzahon What did you do? I'm having the same issue

I ended up using a different solution. Using [https://www.npmjs.com/package/hark](hark) I would connect it to the audio stream, get the volume level from it, and then adjust the width of a div to simulate  a visualizer bar
