### ISSUE TITLE
How to use mp3 url link as the source for  <AudioSpectrum/>

### ISSUE THREAD

**Issue by Oscarwang666** [hu-ke/react-audio-spectrum#17]
sources
```
audios: [ 
                {
                    id: 1,
                    audio_name: 'Intro1',
                    audio_url: "http://somewebsitexxx.mp4", // fetch from server
                    playing: false,
                },
                {
                    id: 2,
                    audio_name: 'Intro2',
                    audio_url: "path/to/file/example.mp3", // read from local file
                    playing: false,
                }
            ]
```

After creatring two `<audio/>`

```
<audio id={i.id}
  src={i.src}
>
```

I was trying to use AudioSpectrum component to play the song :

```
audios.map((i)=>{
                        <AudioSpectrum
                        id={i.id}
                        height={300}
                        width={559}
                        audioId={i.id}
                        capColor={'red'}
                        capHeight={2}
                        meterWidth={2}
})
```

The problem is that i can only play the audio and see dynamic image with the second one (the one read from local path )
so i am wondering if you can tell me how do i deal with the first one which is the one with mp3 url link

However, i was trying to convert the url to file or audio type cause the file one works but i still not able to play the first one .

```
let a = new Audio("http://somewebsitexxx.mp4")
a.id = 123
<AudioSpectrum
  id={a.id}
  audioEle={a.src}
/>
```
output :
https://i.imgur.com/yGEwedm.png

ps. I think i can just use the audio API to play mp3 url link but then how can i use `  <AudioSpectrum/>` to dislpay image separately ?

audio API :
https://www.codegrepper.com/code-examples/whatever/how+to+play+audio+from+server+reactjs

**Comment by jimmyl02** [comment]
I'm not sure why the `getByteFrequencyData` isn't working for remote audio sources made via `new Audio()`. A workaround is to use HTML `<audio>` tags with crossOrigin set to anonymous. This seems to work for me.

Full example

```
<audio id="audio-element1"
src='your_url'
crossOrigin='annonymous'
>
</audio>
<AudioSpectrum
    id="audio-canvas"
    height={200}
    width={300}
    audioId='audio-element1'
    ...
    />
```

You can invoke the audio to play via javascript and the spectrum should work.

**Comment by hu-ke** [comment]
Maybe same issue as `CORS issue` #29 ? I have updated readme for it. you can try link: https://reader.guru/medias/How-Long-Will-I-Love-You.mp3 for testing.
