### ISSUE TITLE
CORS problem

### ISSUE THREAD

**Issue by akaadream** [hu-ke/react-audio-spectrum#29]
Hello,

The library returne me an CORS issue when i'm trying to use AudioSpectrum on my project. Do you know why ?
Here is the following error :
![image](https://user-images.githubusercontent.com/18325858/125310132-9b66af00-e332-11eb-9869-8cd8483ea82f.png)

Here is the code : 
```html
<audio src={question.preview} id={"audio-element"} autoPlay={true} />
<AudioSpectrum
    id={"audio-canvas"}
    height={200}
    width={300}
    audioId={"audio-element"}
    capColor={'red'}
    capHeight={2}
    meterWidth={2}
    meterCount={512}
    meterColor={[
        {stop: 0, color: '#f00'},
        {stop: 0.5, color: '#0cd7fd'},
        {stop: 1, color: 'red'}
    ]}
    gap={4}
/>
```

Thanks in advance !

**Comment by x3malmusic** [comment]
your audio tag should have prop crossOrigin="anonymous" in order to work

**Comment by jonCroatanUto** [comment]
Thanks, it work's now

**Comment by hu-ke** [comment]
Thank you for pointing it out, i have updated the doc for CORS issue.
