### ISSUE TITLE
Build Instruction / Documentation

### ISSUE THREAD

**Issue by maximotus** [hu-ke/react-audio-spectrum#34]
Hey,

could you provide some information on how to build the src/AudioSpectrum.js file appropriately (so I can adapt the module locally and maybe add some PRs)?
Are you using gulp? If yes, could you provide the gulpfile.js please? :)

Thanks and best,
maximotus

**Comment by hu-ke** [comment]
Previous local development is troublesome. I have changed the project scaffold to [template-icestark-module](https://github.com/ice-lab/material-templates/blob/master/packages/template-icestark-module-ts/template/component/demo/usage.md.ejs).After `npm install`, simply run `npm run start` for local preview and development.
