### ISSUE TITLE
it works on safari?

### ISSUE THREAD

**Issue by hitzu** [hu-ke/react-audio-spectrum#7]
in the project example:

on chrome works 

![Chrome gif](https://i.ibb.co/r6v6kRw/chrome.gif)

on safari doesnt work 

![safari git](https://i.ibb.co/wMySgSc/safari.gif)

someone know how i can solve this issue?

**Comment by LarryBattle** [comment]
`App.js` https://github.com/hu-ke/react-audio-spectrum/blob/master/exmaple/react-audio-spectrum-demo/src/App.js#L43
```
this.audioEle1.oncanplay = (e) => {
      // safari不允许自动播放
      if (this.isSafari()) {
        return
      }
      this.play1()
    }
```
The comment says `safari不允许自动播放` which translates to `Safari does not allow autoplay.`.

But I tried this on Chrome 80 and the devtools console shows this.

```
AudioSpectrum.js:131 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
n.prepareAPIs @ AudioSpectrum.js:131
registerServiceWorker.js:64 Content is cached for offline use.
App.js:75 Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD
```

Maybe this might work. (untested)
https://github.com/hu-ke/react-audio-spectrum/blob/master/exmaple/react-audio-spectrum-demo/src/App.js#L98
```js
  play3 = () => {
    this.audioEle3 = new Audio(this.playlist[3])
    this.audioEle3.play()
    this.setState({
      audioStatus3: 'PLAYING'
    })
  }
```

**Comment by SamuelPelletier** [comment]
Hello,

The spectrum can't work on Safari because Apple dit not fix `getByteFrequencyData ` function with a previous implementation of `createMediaElementSource `.
Just wait/hope Apple fix it.

**Comment by maximotus** [comment]
Im not that deep in the topic, but have you tried using this package?
[standardized-audio-context](https://github.com/chrisguttandin/standardized-audio-context)

**Comment by hu-ke** [comment]
> in the project example:
> 
> on chrome works
> 
> ![Chrome gif](https://camo.githubusercontent.com/ecc6d744a1514c34c1432d0fe2c7df212c56ef1b4e80fd268e15684625e79a00/68747470733a2f2f692e6962622e636f2f723676366b52772f6368726f6d652e676966) [ ![Chrome gif](https://camo.githubusercontent.com/ecc6d744a1514c34c1432d0fe2c7df212c56ef1b4e80fd268e15684625e79a00/68747470733a2f2f692e6962622e636f2f723676366b52772f6368726f6d652e676966) ](https://camo.githubusercontent.com/ecc6d744a1514c34c1432d0fe2c7df212c56ef1b4e80fd268e15684625e79a00/68747470733a2f2f692e6962622e636f2f723676366b52772f6368726f6d652e676966) [ ](https://camo.githubusercontent.com/ecc6d744a1514c34c1432d0fe2c7df212c56ef1b4e80fd268e15684625e79a00/68747470733a2f2f692e6962622e636f2f723676366b52772f6368726f6d652e676966)
> 
> on safari doesnt work
> 
> ![safari git](https://camo.githubusercontent.com/3dd0a737585a18ab0e6113feeeaacf32ec2694d2d20097d19f6d3e03a0b73461/68747470733a2f2f692e6962622e636f2f774d79536753632f7361666172692e676966) [ ![safari git](https://camo.githubusercontent.com/3dd0a737585a18ab0e6113feeeaacf32ec2694d2d20097d19f6d3e03a0b73461/68747470733a2f2f692e6962622e636f2f774d79536753632f7361666172692e676966) ](https://camo.githubusercontent.com/3dd0a737585a18ab0e6113feeeaacf32ec2694d2d20097d19f6d3e03a0b73461/68747470733a2f2f692e6962622e636f2f774d79536753632f7361666172692e676966) [ ](https://camo.githubusercontent.com/3dd0a737585a18ab0e6113feeeaacf32ec2694d2d20097d19f6d3e03a0b73461/68747470733a2f2f692e6962622e636f2f774d79536753632f7361666172692e676966)
> 
> someone know how i can solve this issue?

I test it on safari and it works fine. Any errors on console?
